/**
 * Typed access to the committed SRD 5.2.1 content bundles. Server-side only by design:
 * clients receive content through server projections/commands, never by importing this package
 * (ADR-0001 server authority; ADR-0007 canonical content format).
 *
 * **The SHAPES moved to `./schemas.ts`; only the LOADERS live here.** `createRequire` below is what
 * makes this module node-only, and the homebrew editor needs the schemas in a browser build to run
 * the same publish check the server runs. Everything in `schemas.ts` is re-exported from here, so
 * no server import site changed and there is still exactly one definition of each schema.
 */
import { createRequire } from "node:module";
import { z } from "zod";
import { ActorDefinitionSchema, type ActorDefinition } from "@vtt/schemas";
import type {
  BackgroundReference, ClassReference, FeatReference, NamePoolReference,
  SpeciesReference, SubclassReference
} from "./character-content.js";
import {
  BackgroundReferenceSchema, ClassReferenceSchema, FeatReferenceSchema, NamePoolReferenceSchema,
  SpeciesReferenceSchema, SubclassReferenceSchema
} from "./character-content.js";
import {
  ArmorReferenceSchema, ConditionReferenceSchema, ContentAttributionSchema, EquipmentReferenceSchema,
  LanguageReferenceSchema, RuleReferenceSchema, SkillReferenceSchema, SpellReferenceSchema, SRD_SKILL_ABILITY,
  WeaponPropertyReferenceSchema, WeaponReferenceSchema,
  type ArmorReference, type ConditionReference, type ContentAttribution, type EquipmentReference, type LanguageReference, type RuleReference,
  type SkillReference, type SpellReference, type WeaponPropertyReference, type WeaponReference
} from "./schemas.js";

/**
 * Content shapes, the canonical SRD vocabularies, and the shared homebrew body-schema map -
 * browser-safe, and re-exported here so every existing server import keeps working unchanged.
 * `schemas.ts` itself re-exports `character-content.ts` and `spell-lists.ts`.
 */
export * from "./schemas.js";

const require = createRequire(import.meta.url);

const cache = new Map<string, unknown>();
function loadBundle<S extends z.ZodTypeAny>(file: string, schema: S): z.output<S> {
  if (!cache.has(file)) cache.set(file, schema.parse(require(`../bundles/${file}`)));
  return cache.get(file) as z.output<S>;
}

/** All SRD 5.2.1 monster definitions, validated on first load and cached. */
export function loadMonsterDefinitions(): readonly ActorDefinition[] {
  return loadBundle("monsters.v1.json", z.array(ActorDefinitionSchema));
}

/** The 15 SRD 5.2.1 conditions as reference text (Blinded, Charmed, ... Unconscious). */
export function loadConditions(): readonly ConditionReference[] {
  return loadBundle("conditions.v1.json", z.array(ConditionReferenceSchema));
}

/** All SRD 5.2.1 spells with structured save/attack/damage/upcast fields plus full text. */
export function loadSpells(): readonly SpellReference[] {
  return loadBundle("spells.v1.json", z.array(SpellReferenceSchema));
}

/** SRD 5.2.1 weapon table (damage, category, ranges). Per-weapon property links are not in the source; see weapon properties. */
export function loadWeapons(): readonly WeaponReference[] {
  return loadBundle("weapons.v1.json", z.array(WeaponReferenceSchema));
}

/** SRD 5.2.1 weapon property and mastery descriptions (Ammunition, Finesse, Cleave, ...). */
export function loadWeaponProperties(): readonly WeaponPropertyReference[] {
  return loadBundle("weapon-properties.v1.json", z.array(WeaponPropertyReferenceSchema));
}

/** SRD 5.2.1 armor table with the fields needed to derive AC (base, dex handling, strength, stealth). */
export function loadArmor(): readonly ArmorReference[] {
  return loadBundle("armor.v1.json", z.array(ArmorReferenceSchema));
}

/** The 18 SRD 5.2.1 skill descriptions, each with the ability its check uses (bundle column first, SRD fallback second). */
export function loadSkills(): readonly SkillReference[] {
  return loadBundle("skills.v1.json", z.array(SkillReferenceSchema)).map((skill) => (
    skill.ability ? skill : { ...skill, ability: SRD_SKILL_ABILITY[skill.id] }
  ));
}

/**
 * The 19 SRD 5.2.1 languages (10 Standard, 9 Rare), each tagged with the table it is printed in.
 *
 * Published as a bundle rather than left as prose because a choice needs a LIST: without this the
 * `species-languages` budget every character is owed ("Common plus two languages") had no options and
 * was therefore never offered at all. See `LanguageReferenceSchema`.
 */
export function loadLanguages(): readonly LanguageReference[] {
  return loadBundle("languages.v1.json", z.array(LanguageReferenceSchema));
}

/**
 * The 268 SRD 5.2.1 magic items, generated by `scripts/build-magic-items.ts` from the vendored
 * `magic-items.md` (258 printed entries; the five `+1, +2, or +3` ladders expand to one row per
 * tier). Content only - rarity, attunement, slot and prose. The mechanics overlay authors the
 * riders on top.
 *
 * Exposed as its own loader as well as folded into `loadEquipment()` so the bundle guard can assert
 * the generated rows without re-deriving them out of the merged catalog.
 */
export function loadMagicItems(): readonly EquipmentReference[] {
  return loadBundle("magic-items.v1.json", z.array(EquipmentReferenceSchema));
}

/**
 * The full addable-equipment catalog: the vendored gear/tools/packs/focus bundle, every weapon and
 * armor mapped from their own bundles into the unified shape, and the generated magic-item bundle.
 * Sorted by name. Extensible - the homebrew update adds entries alongside these.
 */
export function loadEquipment(): readonly EquipmentReference[] {
  // Normalize the hand-authored gear so every catalog entry has a uniform shape - `weapon`/`armor`
  // are always present (null when absent), so a consumer can branch on `item.weapon === null`.
  const gear: EquipmentReference[] = loadBundle("equipment.v1.json", z.array(EquipmentReferenceSchema)).map((item) => ({
    ...item, weapon: item.weapon ?? null, armor: item.armor ?? null
  }));
  // A mundane SRD row's magic-item fields, spelled once. `EquipmentReferenceSchema` gives these
  // `.default()`s, which makes them REQUIRED on the parsed output type - and these two rows are
  // hand-built object literals rather than parsed, so they have to state them.
  const mundane = (): Pick<EquipmentReference, "isMagic" | "cursed" | "casts" | "grantsFeatIds" | "tags" | "actions" | "effects" | "modifiers"> =>
    ({ isMagic: false, cursed: false, casts: [], grantsFeatIds: [], tags: [], actions: [], effects: [], modifiers: [] });
  // The mapped-in rows carry their OWN bundle's source through the fold, so a homebrew weapon or
  // armor row stays homebrew once it is in the unified catalog. They also stamp `slot`, the
  // mechanical hook, alongside the `category` slug they already stamped - a no-op today (every
  // consumer still falls back to `category`) and what makes an open homebrew category derive AC.
  const weapons: EquipmentReference[] = loadWeapons().filter((weapon) => !weapon.improvised).map((weapon) => ({
    id: weapon.id, name: weapon.name, source: weapon.source, category: "weapon", slot: "weapon", costGp: null, weightLb: null, description: null,
    weapon: { category: weapon.category, damageDice: weapon.damage.dice, damageType: weapon.damage.type, rangeFeet: weapon.rangeFeet, longRangeFeet: weapon.longRangeFeet, mastery: weapon.mastery, properties: weapon.properties }, armor: null,
    ...mundane()
  }));
  const armor: EquipmentReference[] = loadArmor().map((piece) => ({
    id: piece.id, name: piece.name, source: piece.source, category: piece.acBase <= 3 ? "shield" : "armor", slot: piece.acBase <= 3 ? "shield" : "armor", costGp: null, weightLb: null, description: null,
    weapon: null, armor: { acBase: piece.acBase, addDexModifier: piece.addDexModifier, dexModifierCap: piece.dexModifierCap, stealthDisadvantage: piece.stealthDisadvantage, strengthRequired: piece.strengthRequired },
    ...mundane()
  }));
  // THE FOURTH SOURCE, and it is a GENERATED bundle rather than 268 more rows in `equipment.v1.json`.
  // That file is hand-authored and is this fold's INPUT; appending would have made it the magic-item
  // ETL's output as well, which is the exact input-and-output entanglement that forced the class
  // overlay to grow a `clears` verb. Every row already carries the whole magic vocabulary from the
  // parse, so unlike `gear` above it needs no normalisation - only the same `weapon`/`armor`-present
  // shape, which the ETL emits explicitly.
  const magic: EquipmentReference[] = loadMagicItems().map((item) => ({
    ...item, weapon: item.weapon ?? null, armor: item.armor ?? null
  }));
  return [...gear, ...weapons, ...armor, ...magic].sort((left, right) => left.name.localeCompare(right.name));
}

/** The 13 SRD 5.2.1 damage-type descriptions. */
export function loadDamageTypes(): readonly ConditionReference[] {
  return loadBundle("damage-types.v1.json", z.array(ConditionReferenceSchema));
}

/** SRD 5.2.1 core rules text grouped by ruleset (D20 Tests, Combat, Damage and Healing, ...). */
export function loadRules(): readonly RuleReference[] {
  return loadBundle("rules.v1.json", z.array(RuleReferenceSchema));
}

/** CC BY 4.0 attribution that must accompany any surface displaying this content. */
export function loadAttribution(): ContentAttribution {
  return loadBundle("attribution.json", ContentAttributionSchema);
}

// ---------------------------------------------------------------------------------------------
// Character-builder bundles.
//
// SEED CONTENT WARNING: the six bundles below currently carry a small, deliberately partial slice of
// the SRD (task packet phase 1.1) - enough real entries to prove the schemas parse and the loaders
// work while the wizard, the rules math, and the UI are built against them in parallel. Full
// transcription (12 classes x 20 levels, 12 subclasses, 9 species, 4 backgrounds, ~20 feats) is
// phases 2 and 5. Do NOT read a missing class as a schema gap.
// ---------------------------------------------------------------------------------------------

/** Playable classes with their 20-row level tables and features-as-data. */
export function loadClasses(): readonly ClassReference[] {
  return loadBundle("classes.v1.json", z.array(ClassReferenceSchema));
}

/** Subclasses, each pointing at its parent `classId`. */
export function loadSubclasses(): readonly SubclassReference[] {
  return loadBundle("subclasses.v1.json", z.array(SubclassReferenceSchema));
}

/** Playable species (size, speed, darkvision, traits); ability increases live on backgrounds in SRD 5.2.1. */
export function loadSpecies(): readonly SpeciesReference[] {
  return loadBundle("species.v1.json", z.array(SpeciesReferenceSchema));
}

/** Backgrounds (ability-score options, origin feat, proficiencies, starting equipment). */
export function loadBackgrounds(): readonly BackgroundReference[] {
  return loadBundle("backgrounds.v1.json", z.array(BackgroundReferenceSchema));
}

/** Feats; each carries its mechanics as an ordinary FeatureRecord. */
export function loadFeats(): readonly FeatReference[] {
  return loadBundle("feats.v1.json", z.array(FeatReferenceSchema));
}

/** Hand-authored per-species name pools feeding the random generator. */
export function loadNames(): readonly NamePoolReference[] {
  return loadBundle("names.v1.json", z.array(NamePoolReferenceSchema));
}

/** Subclasses belonging to one class, in bundle order. */
export function subclassesForClass(classId: string): readonly SubclassReference[] {
  return loadSubclasses().filter((subclass) => subclass.classId === classId);
}

/** Name pools for one species, or undefined when that species has none authored yet. */
export function namesForSpecies(speciesId: string): NamePoolReference | undefined {
  return loadNames().find((pool) => pool.speciesId === speciesId);
}
